"""queue on-demand sync requests

The MCP server may not contact a vendor, so a tool that asks for a resync has
nowhere to put the ask. This table is that place: the server appends, the
vendor's worker reads and runs. The two processes share nothing else but the
database file, and now they do not need to.

Purely additive. An empty table means nobody has asked for anything, which is
what every worker already assumes when it wakes on schedule.

Revision ID: 23c9002d1e93
Revises: 685aa8fe1a5c
Created: 2026-08-30 15:14:39.357936
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "23c9002d1e93"
down_revision: str | None = "685aa8fe1a5c"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requested_at", sa.DateTime(), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("served_at", sa.DateTime(), nullable=True),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sync_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sync_requests_requested_at"), ["requested_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sync_requests_source"), ["source"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sync_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_requests_source"))
        batch_op.drop_index(batch_op.f("ix_sync_requests_requested_at"))

    op.drop_table("sync_requests")
    # ### end Alembic commands ###
