"""record sync runs

A worker that ran and found nothing and a worker that has been dead a week
leave the same evidence: no new rows. This table separates them by recording
the attempt, so a gap in the weekly report can be read as a rest day or as a
broken sync rather than guessed at.

Purely additive. Nothing reads ``sync_runs`` before a worker has written to it,
and an empty table is reported as "never ran" rather than as healthy.

Revision ID: 685aa8fe1a5c
Revises: 70260574cd65
Created: 2026-08-25 23:01:09.824012
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "685aa8fe1a5c"
down_revision: str | None = "70260574cd65"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=True),
        sa.Column("counts", sa.JSON(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sync_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sync_runs_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_sync_runs_started_at"), ["started_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sync_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_runs_started_at"))
        batch_op.drop_index(batch_op.f("ix_sync_runs_source"))

    op.drop_table("sync_runs")
    # ### end Alembic commands ###
