"""intake entries replace daily nutrition

The daily-total row could only be written once: a second call overwrote the
first and nulled any field it did not repeat, so logging lunch destroyed
breakfast. Nobody knows their day's total at the moment they eat.

Autogenerate produced the schema half of this and would have dropped
``nutrition`` with the rows still in it. The copy below is hand-written, because
alembic cannot know that a daily total becomes one entry.

Revision ID: 70260574cd65
Revises: e9cbbc6f3584
Created: 2026-08-24 19:48:35.313501
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "70260574cd65"
down_revision: str | None = "e9cbbc6f3584"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

# Marks an entry this revision created from a daily row, so the downgrade can
# tell a migrated total from something logged afterwards.
MIGRATED_TOTAL = "(migrated daily total)"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "intake_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("item", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("qty", sa.Float(), nullable=True),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("kcal", sa.Integer(), nullable=True),
        sa.Column("protein_g", sa.Float(), nullable=True),
        sa.Column("fat_g", sa.Float(), nullable=True),
        sa.Column("carbs_g", sa.Float(), nullable=True),
        sa.Column("ml", sa.Integer(), nullable=True),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("intake_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_intake_entries_date"), ["date"], unique=False)

    # --- data, which autogenerate cannot infer -----------------------------
    # Every daily row becomes a single entry. Noon local is a deliberate
    # fiction: the old shape recorded a day and not a time, and midnight would
    # place every migrated meal exactly on a boundary a timezone change moves.
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT * FROM nutrition")).mappings().all()
    for row in rows:
        day = str(row["date"])
        conn.execute(
            sa.text(
                "INSERT INTO intake_entries (at, date, item, kcal, protein_g, fat_g,"
                " carbs_g, note) VALUES (:at, :date, :item, :kcal, :protein_g, :fat_g,"
                " :carbs_g, :note)"
            ),
            {
                "at": f"{day} 12:00:00",
                "date": day,
                "item": MIGRATED_TOTAL,
                "kcal": row["kcal"],
                "protein_g": row["protein_g"],
                "fat_g": row["fat_g"],
                "carbs_g": row["carbs_g"],
                "note": row["note"],
            },
        )
        # The four supplement booleans become ordinary entries: a supplement is
        # a thing taken at a time, which is what an entry is.
        for name in ("creatine", "magnesium", "vitamin_d", "probiotic"):
            if row[name]:
                conn.execute(
                    sa.text(
                        "INSERT INTO intake_entries (at, date, item, qty, unit, note)"
                        " VALUES (:at, :date, :item, 1.0, 'serving', :note)"
                    ),
                    {"at": f"{day} 12:00:00", "date": day, "item": name, "note": MIGRATED_TOTAL},
                )

    op.drop_table("nutrition")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nutrition",
        sa.Column("date", sa.DATE(), nullable=False),
        sa.Column("kcal", sa.INTEGER(), nullable=True),
        sa.Column("protein_g", sa.FLOAT(), nullable=True),
        sa.Column("fat_g", sa.FLOAT(), nullable=True),
        sa.Column("carbs_g", sa.FLOAT(), nullable=True),
        sa.Column("creatine", sa.BOOLEAN(), nullable=False),
        sa.Column("magnesium", sa.BOOLEAN(), nullable=False),
        sa.Column("vitamin_d", sa.BOOLEAN(), nullable=False),
        sa.Column("probiotic", sa.BOOLEAN(), nullable=False),
        sa.Column("note", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("date"),
    )
    # --- data, and this direction is lossy ---------------------------------
    # Entries carry a time and a granularity the daily row has nowhere to put.
    # Going back sums each day and keeps that; the individual meals are gone.
    # Anyone running this should have the pre-migration backup soma-migrate
    # takes, which is not lossy.
    conn = op.get_bind()
    totals = (
        conn.execute(
            sa.text(
                "SELECT date, SUM(kcal) AS kcal, SUM(protein_g) AS protein_g,"
                " SUM(fat_g) AS fat_g, SUM(carbs_g) AS carbs_g FROM intake_entries"
                " GROUP BY date"
            )
        )
        .mappings()
        .all()
    )
    for row in totals:
        supplements = {
            name: bool(
                conn.execute(
                    sa.text("SELECT 1 FROM intake_entries WHERE date = :d AND item = :i LIMIT 1"),
                    {"d": row["date"], "i": name},
                ).first()
            )
            for name in ("creatine", "magnesium", "vitamin_d", "probiotic")
        }
        conn.execute(
            sa.text(
                "INSERT INTO nutrition (date, kcal, protein_g, fat_g, carbs_g,"
                " creatine, magnesium, vitamin_d, probiotic)"
                " VALUES (:date, :kcal, :protein_g, :fat_g, :carbs_g,"
                " :creatine, :magnesium, :vitamin_d, :probiotic)"
            ),
            {**row, **supplements},
        )

    with op.batch_alter_table("intake_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_intake_entries_date"))

    op.drop_table("intake_entries")
    # ### end Alembic commands ###
