"""baseline schema

Revision ID: e9cbbc6f3584
Revises: 
Created: 2026-08-24 19:39:51.724488
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = 'e9cbbc6f3584'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sport', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('tss', sa.Float(), nullable=True),
    sa.Column('avg_power', sa.Float(), nullable=True),
    sa.Column('np', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('work_kj', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_activity_source_id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_source'), ['source'], unique=False)

    op.create_table('body',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('calendar_sync',
    sa.Column('workout_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('google_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('workout_id')
    )
    op.create_table('daily_health',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('sleep_duration_s', sa.Integer(), nullable=True),
    sa.Column('hrv_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hrv_ms', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('body_battery_high', sa.Integer(), nullable=True),
    sa.Column('body_battery_low', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('nutrition',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('creatine', sa.Boolean(), nullable=False),
    sa.Column('magnesium', sa.Boolean(), nullable=False),
    sa.Column('vitamin_d', sa.Boolean(), nullable=False),
    sa.Column('probiotic', sa.Boolean(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('planned_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workout_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('target_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_planned_source_id')
    )
    with op.batch_alter_table('planned_workouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planned_workouts_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_planned_workouts_source'), ['source'], unique=False)

    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('test_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ftp', sa.Integer(), nullable=True),
    sa.Column('map_w', sa.Integer(), nullable=True),
    sa.Column('ac_w', sa.Integer(), nullable=True),
    sa.Column('nm_w', sa.Integer(), nullable=True),
    sa.Column('lthr', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('rider_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tests_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tests_date'))

    op.drop_table('tests')
    with op.batch_alter_table('planned_workouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planned_workouts_source'))
        batch_op.drop_index(batch_op.f('ix_planned_workouts_date'))

    op.drop_table('planned_workouts')
    op.drop_table('nutrition')
    op.drop_table('daily_health')
    op.drop_table('calendar_sync')
    op.drop_table('body')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_source'))
        batch_op.drop_index(batch_op.f('ix_activities_date'))

    op.drop_table('activities')
    # ### end Alembic commands ###
